### ISSUE TITLE
[FEATURE] `vlt pkg`

### ISSUE THREAD

**Issue by darcyclarke** [vltpkg/vltpkg#105]
### Description
Implement a command for managing `package.json` (similar to `npm`).

### Implementation

```bash
vlt pkg get [<key> [<key> ...]]
vlt pkg set <key>=<value> [<key>=<value> ...]
vlt pkg set [<array>[<index>].<key>=<value> ...]
vlt pkg set [<array>[].<key>=<value> ...]
vlt pkg <rm|remove|unset|delete> <key> [<key> ...]
```

> [!Note]
> `vlt pkg get` without a key should return the entire contents of `package.json`

**Comment by lukekarrys** [comment]
We have this!
