### ISSUE TITLE
running any vlt command errors with INVALID_ARG_TYPE

### ISSUE THREAD

**Issue by lukekarrys** [vltpkg/vltpkg#229]
![image](https://github.com/user-attachments/assets/d2241685-7ec0-449e-ac56-e537427812d7)

https://x.com/ethomson/status/1854903126534353369?s=46

**Comment by isaacs** [comment]
Doesn't work on node 20.10.0. Upgrade to the latest node 20, or use node 22.

It's unlikely that we're going to fix this, since the plan is to (relatively soon) ship vlt as a standalone bin with a known-good runtime. So, doing platform-specific workarounds or polyfills doesn't make a lot of sense.
