### ISSUE TITLE
[FEATURE] replace the bespoke `;` formatting with `URL`s for `DepID`s

### ISSUE THREAD

**Issue by darcyclarke** [vltpkg/vltpkg#96]
### Description
Currently `DepID`s are a net-new string format that has no conceptual basis outside of `vlt` with the primary purpose being to encode the type of & resolved package id. This _may_ be fine if these were never to be seen by end-users but they are _very_ likely to bubble up during any kind of error handling/debugging & have quickly become fundamental identifiers used in various places in code/config (making it very likely to spill out into end-user output/documentation/config).

### Suggestion
Use URLs. Instead of creating a net-new format, leverage the existing `URL` format & use a basic lookup table to identify a `DepID`'s `type` based on it's `protocol`.

> [!IMPORTANT]
> Not all URLs would be valid/supported `DepID`s but **all** `DepID`s would be valid URLs - ex. `tel:`, `telnet:`, `mailto:`, `news:`, `urn:`  & `ldap:` aren't likely `type`s/sources for packages we'd ever support (although we should consider protecting against users configuring custom registry protocols which would collide with these & other [known/common URI schemes](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml)).

### Examples

> [!NOTE]
> For brevity/clarity, values are not percent encoded but all `DepID`s should likely take the form post `encodeURIComponent` so as to be valid directory names.
 
| Before | After |
| --- | --- |
| `registry;;foo@1.0.0` or `;;foo@1.0.0`, if #89 happens | `npm:foo@1.0.0` |
| `registry;vlt;x@1.2.3` | `vlt:x@1.2.3` |
| `file;./x.tgz` | `file:./x.tgz` |
| `git;git+ssh://host.com/x.git` | `git+ssh://host.com/x.git` |
| `git;github:a/b;branch` | `github:a/b#branch` |
| `remote;https://x.com/x.tgz` | `https://x.com/x.tgz` |
| `workspace;a` | `workspace:a` |

### Implementation

An example `types`/`protocols` lookup table seems pretty straightforward (can change/expand as needed):

```ts
const types = {
  npm: 'registry',
  git: 'git',
  'git+ssh': 'git',
  'git+http': 'git',
  'git+https': 'git',
  'git+ftp': 'git',
  'git+file': 'git',
  'git+rsync': 'git',
  github: 'git',
  bitbucket: 'git',
  gitlab: 'git',
  http: 'remote',
  https: 'remote',
  file: 'file',
  workspace: 'workspace'
}
```

A comparable/efficient split+lookup to the existing [split+switch](https://github.com/vltpkg/vltpkg/blob/main/src/dep-id/src/index.ts#L80-L107) would be:

```ts
const type = types[decodeURIComponent(DepIDString).split(':', 2)[0]]
```

**Comment by isaacs** [comment]
What we have is working now. The `;` had to change, but it's nicely terse and unambiguous.
